### ISSUE TITLE
Triangle is misspelled in several places.

### ISSUE THREAD

**Issue by alamaral** [Seeed-Studio/Small_ePaper_Shield#10]
drawTraingle should be drawTriangle.

diff --git a/README.md b/README.md
index 4deaf67..1ff1662 100644
--- a/README.md
+++ b/README.md
@@ -145,7 +145,7 @@ Example:<pre>
     EPAPER.drawVerticalLine(150, 20, 60);</pre>
 
 
-### 16. void drawTraingle( int poX1, int poY1, int poX2, int poY2, int poX3, int poY3);
+### 16. void drawTriangle( int poX1, int poY1, int poX2, int poY2, int poX3, int poY3);
 The function can be used to draw a triangle. It is formed by three points.
 
 * poX1(poX2,poX3): the X-coordinate of the triangle one point.
diff --git a/ePaper.cpp b/ePaper.cpp
index 7e6256f..59b1ca7 100644
--- a/ePaper.cpp
+++ b/ePaper.cpp
@@ -598,18 +598,18 @@ void ePaper::fillCircle(int poX, int poY, int r) {
 }
 
 /*********************************************************************************************************
-** Function name:           drawTraingle
-** Descriptions:            drawTraingle
+** Function name:           drawTriangle
+** Descriptions:            drawTriangle
 *********************************************************************************************************/
-void ePaper::drawTraingle(int poX1, int poY1, int poX2, int poY2, int poX3, int poY3) {
+void ePaper::drawTriangle(int poX1, int poY1, int poX2, int poY2, int poX3, int poY3) {
     drawLine(poX1, poY1, poX2, poY2);
     drawLine(poX1, poY1, poX3, poY3);
     drawLine(poX2, poY2, poX3, poY3);
 }
 
 /*********************************************************************************************************
-** Function name:           drawTraingle
-** Descriptions:            drawTraingle
+** Function name:           fillRectangle
+** Descriptions:            fillRectangle
 *********************************************************************************************************/
 void ePaper::fillRectangle(int poX, int poY, int len, int width) {
     for (int i = 0; i < width; i++) {
diff --git a/ePaper.h b/ePaper.h
index 59b6e3b..668d90d 100644
--- a/ePaper.h
+++ b/ePaper.h
@@ -134,7 +134,7 @@ class ePaper {
     void drawRectangle(int poX, int poY, int len, int width);
     void fillRectangle(int poX, int poY, int len, int width);
     void fillCircle(int poX, int poY, int r);
-    void drawTraingle(int poX1, int poY1, int poX2, int poY2, int poX3, int poY3);
+    void drawTriangle(int poX1, int poY1, int poX2, int poY2, int poX3, int poY3);
 };
 
 extern ePaper EPAPER;
diff --git a/keywords.txt b/keywords.txt
index 5dc551a..1ab5aa1 100644
--- a/keywords.txt
+++ b/keywords.txt
@@ -44,7 +44,7 @@ drawVerticalLine      KEYWORD2
 drawRectangle  KEYWORD2
 fillRectangle  KEYWORD2
 fillCircle     KEYWORD2
-drawTraingle   KEYWORD2
+drawTriangle   KEYWORD2
 
 #######################################
 #      Constants       (LITERAL1)
@@ -55,4 +55,4 @@ EPD_2_7       LITERAL1
 DIRNORMAL      LITERAL1
 DIRLEFT        LITERAL1
 DIRRIGHT       LITERAL1
-DIRDOWN        LITERAL1
\ No newline at end of file
+DIRDOWN        LITERAL1

**Comment by lakshanthad** [comment]
Hi @alamaral,

It is fixed.
