### ISSUE TITLE
nRF52840 compile errors

### ISSUE THREAD

**Issue by BitLox** [Seeed-Studio/Small_ePaper_Shield#11]
Was wondering if I could get some input here!
I compiled this for use with Arduino DUE (and also the MEGA) a while back and it seems to work well albeit slow.

I'd like to use this with the nRF5280 chip series, the DK pinout is the same as DUE so no problems there.
I had to mask most of the '#define pgm_read_byte(x) (*(x))' parts, because they bark about being redefined, so that works.

The problem is when I compile it throws an error claiming no return statement on the clear and display functions:
```
due_sd_epaper.cpp: In member function 'unsigned char sd_epaper::clear()':
due_sd_epaper.cpp:259:1: error: no return statement in function returning non-void [-Werror=return-type]

due_ePaper.cpp: In member function 'unsigned char ePaper::display()':
due_ePaper.cpp:547:1: error: no return statement in function returning non-void [-Werror=return-type]
```

This code compiles and runs on both DUE and MEGA, but somehow wants a return on nRF52.

I put in a dummy` return 1` statement in both of them - the code then compiles on all three but doesn't display anything on the nRF52840.

Any suggestions?

Arduino 1.8.19 / macOS 15.1.1 / Adafruit bootloader / nRF52840 DK pca10056

**Comment by BitLox** [comment]
BTW I added the board names in the appropriate spots such as 
```
#if defined(__AVR_ATmega32U4__) || defined(__AVR_ATmega328P__)
    EPD.image_sd();
#elif defined(__AVR_ATmega1280__) || defined(__AVR_ATmega2560__)|| defined(__SAM3X8E__)|| defined(__SAM3A8C__) || defined(NRF52840_XXAA)
    EPD.image_sram(eSD.sram_image);
#endif
```

**Comment by Pillar1989** [comment]
This is a very old product, when this product was defined, nrf52840 had not yet appeared, sorry, can not be supported. @BitLox  We can not find the corresponding hardware, if you happen to have this hardware, if you are interested in fixing and supporting, we are very welcome.

**Comment by BitLox** [comment]
Oh I have the hardware, was just wondering if you had any insight as to why it would throw such an error.
Don't expect you to "support" it, just asking if you had any suggestions. 
I'd be happy to push any changes once I figure it out.

**Comment by baorepo** [comment]
The two compilation errors indicate that in your C++ program, two member functions do not correctly return a value as required by their declared return type. The errors occur in the due_sd_epaper.cpp and due_ePaper.cpp files, specifically involving the sd_epaper::clear() and ePaper::display() member functions.

sd_epaper::clear()
The member function clear() is declared to return an unsigned char type, but there is no return statement within the function body.
According to the error message, the function body ends at line 259, and there is no return statement on that line.
ePaper::display()
Similarly, the member function display() is also declared to return an unsigned char type, but there is no return statement within the function body.
The function body ends at line 547, and there is no return statement on that line as well.
Solution
To resolve these compilation errors, you need to add a return statement at an appropriate location in each function, ensuring that it returns a value of the unsigned char type. The specific return value depends on the function's intended purpose and context, but typically for such functions, the return value may be used to indicate the success or failure of the operation.

Example Correction
Assuming that the clear() and display() functions are used to perform some operation and should return a value indicating success (e.g., 0 for success, other values for errors), you can modify them as follows:
```c++
// In due_sd_epaper.cpp
unsigned char sd_epaper::clear() {
    // Code to perform the clearing operation
    // ...

    // Assuming the clearing operation is successful, return 0
    return 0;
}

// In due_ePaper.cpp
unsigned char ePaper::display() {
    // Code to perform the display operation
    // ...

    // Assuming the display operation is successful, return 0
    return 0;
}
```
Notes
Ensure that the returned value aligns with the function's expected logic.
If the function may encounter error conditions, consider returning different values to indicate different error states.
In actual projects, adding more error handling and status checks may be necessary to ensure the robustness of the functions.
By making the above modifications, your code should compile successfully, and these member functions will correctly return values according to their declared return types.

**Comment by Pillar1989** [comment]
@BitLox  I'll close this issues and open it again if you need to discuss it in the future.
